export const environment = {
  production: false,
  twitter_auth_url_v_1: 'https://api.twitter.com/oauth/access_token',
  twitter_auth_url: 'https://api.twitter.com/2/oauth2/token',
  twitter_url: 'https://api.twitter.com/2',
  client_id_twitter: 'eFlHTkNwVUZzUkN4RXRnQXFSSDY6MTpjaQ',
  redirect_uri: 'https://localhost:4200/channels',
  fb_app_id: '484004453229056',
  fb_client_secret: 'a29f96cc1b76aa2a9863604a89706e23',
  FB_AUTH_URL: 'https://graph.facebook.com/v13.0',
  FB_GRAPH: 'https://graph.facebook.com/',
  twitterConsumerKey: 'eFlHTkNwVUZzUkN4RXRnQXFSSDY6MTpjaQ',
  twitterConsumerSecret: 'Me7nSwiqlooPcvx8lHumYoDINGxIdSWwuKLpe32LwEsLyL0RbV',
  linkedin_client_id: '78mpkeccm3h7f8',
  linkedin_client_secret: 'NKpXktRXikhBvfFc',
  twitter_app_key: '8COqs2uPcZZL20BNhFEObU711',
  twitter_app_secret: 'm7OewS57ByrNbnF8TdFyD05fMqLFnwSN7KRwrUEfmqL8WcXKET',
  LINKEDIN: 'https://www.linkedin.com',
};
